AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation template to deploy an AWS Lambda function for processing FPL data and storing CSV outputs in S3.

Resources:
  FantasyDraftBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "fantasy-pl-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FantasyDraftBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FantasyDraftBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FantasyDraftBucket}/*"

  FantasyDraftLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FantasyDraftLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FantasyDraftS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${FantasyDraftBucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  FantasyDraftLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fpl-data-munger/
      Description: Lambda function to process fantasy_draft.json and store CSV outputs in S3.
      Environment:
        Variables:
          S3_BUCKET: !Ref FantasyDraftBucket
      FunctionName: FantasyDraftProcessor
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Runtime: python3.13
      Role: !GetAtt FantasyDraftLambdaRole.Arn
      Timeout: 60
