name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: aws-actions/setup-sam@v2

      - id: build-data-munger
        name: SAM build
        run: sam build --template fpl-data-munger/fpl-data-munger.yaml --use-container

      - id: deploy-data-munger
        name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name FPLDataMunger --s3-bucket github-package-builds-${{ env.region }} --capabilities CAPABILITY_IAM --region ${{ env.region }}

      - name: Describe stacks
        run: |
          aws cloudformation describe-stacks --stack-name FPLDataMunger --output text

